name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Boost
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
        else
          brew install boost
        fi
      
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        
    - name: Build
      run: |
        cd build
        make
        
    - name: Run
      run: |
        cd bin
        ./example_PE01